// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwFTsUpTPrgdYpJAwtfKW-BzL3ZO5KHo',
    appId: '1:740367913594:web:73c0096c4e1c2d12ae21c3',
    messagingSenderId: '740367913594',
    projectId: 'intellichat-f6b08',
    authDomain: 'intellichat-f6b08.firebaseapp.com',
    storageBucket: 'intellichat-f6b08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjXaahh4kHmyGK7B6AvACVRYOMisqXIjw',
    appId: '1:740367913594:android:521e593bb8b6501cae21c3',
    messagingSenderId: '740367913594',
    projectId: 'intellichat-f6b08',
    storageBucket: 'intellichat-f6b08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRADzsDsPaoigH6WhXBnhsHPUtACrKh4',
    appId: '1:740367913594:ios:d409dab2489bff31ae21c3',
    messagingSenderId: '740367913594',
    projectId: 'intellichat-f6b08',
    storageBucket: 'intellichat-f6b08.appspot.com',
    androidClientId: '740367913594-ij77g0ie09c0phibq3mee2s7brpbrr3a.apps.googleusercontent.com',
    iosClientId: '740367913594-i36qjl9jvrdec0joqiamcf4rl2sussgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvRADzsDsPaoigH6WhXBnhsHPUtACrKh4',
    appId: '1:740367913594:ios:d409dab2489bff31ae21c3',
    messagingSenderId: '740367913594',
    projectId: 'intellichat-f6b08',
    storageBucket: 'intellichat-f6b08.appspot.com',
    androidClientId: '740367913594-ij77g0ie09c0phibq3mee2s7brpbrr3a.apps.googleusercontent.com',
    iosClientId: '740367913594-i36qjl9jvrdec0joqiamcf4rl2sussgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJwFTsUpTPrgdYpJAwtfKW-BzL3ZO5KHo',
    appId: '1:740367913594:web:19fa5b8fe98c3638ae21c3',
    messagingSenderId: '740367913594',
    projectId: 'intellichat-f6b08',
    authDomain: 'intellichat-f6b08.firebaseapp.com',
    storageBucket: 'intellichat-f6b08.appspot.com',
  );

}